### PR TITLE
Support for old systemd

### PR DESCRIPTION
**Pull request by kiorky**
Allow to run on boxes without the system-service syscall filter group

Digging a bit more on #1, seems that on ubuntu1804, the system-service syscall group filter does not exist yet.

rel #1

### CODE REVIEW

**Comment by s-hamann** [comment]
Thank you for digging down on this.
It seems that `@system-service` was introduced in systemd 239, which was released on 2018-06-22, well over four years ago. I do not think it makes sense to introduce and maintain workarounds for software this old.
If you have the need to support very old versions of systemd (pre 239), I suggest that you maintain your own fork of this role.
I have neither the capacity nor the need to maintain, test and support this.

**Comment by kiorky** [comment]
Sorry, i may ask you to reconsider this as for example ubuntu1804 is still to be around for years (LTS+ESM)[https://ubuntu.com/about/release-cycle] ...

**Comment by kiorky** [comment]
Sorry, i may ask you to reconsider this as for example ubuntu1804 is still to be around for years [LTS+ESM](https://ubuntu.com/about/release-cycle) ...

**Comment by s-hamann** [comment]
My roles are written for my own personal use and published here in the hope that they may be useful to someone else as well. However, I do not strive to support every possible configuration or system. Personally, I have no use for Ubuntu, nor for systems running severely outdated software.
Your needs are different and that is fine. Feel free to build upon my code and turn it into something that is useful to you.

**Pull request closed without merging**
